# ESCOTT results cleanup

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
ls "../model_scores/ESCOTT"

ALPH_ELIME_Markin_2021.csv      P11436_normPred_evolCombi.txt
ALPH_ELIME_Markin_2021.txt      P11436.out
ALPH.fasta                      P62593.fasta
ALPH_jet.res                    P62593_jet.res
ALPH_normPred_evolCombi.txt     P62593_normPred_evolCombi.txt
ALPH.out                        P62593.out
AMIE_PSEAE_Wrenbeck_2017.csv    PHO4.fasta
blah.txt                        PHO4_jet.res
BLAT_ECOLX_Stiffler_2015.csv    PHO4_normPred_evolCombi.txt
computePred.R                   PHO4.out
default.conf                    PHO4_YEAST_Aditham_2021.csv
DLG4_HUMAN_Zarin_2024.csv       pred.R
DLG4_HUMAN_Zarin_2024.txt       PSD95pdz3.fasta
DLG4_HUMAN_Zarin_2025.csv       PSD95pdz3_jet.res
HTHTR_SALTY_dOelsnitz_2025.csv  PSD95pdz3_normPred_evolCombi.txt
lw-i.7.txt                      PSD95pdz3_original.pdb
MNTH_DEIRA_Berry_2025.csv       PSD95pdz3.out
MNTH_DEIRA_Berry_2025.txt       RamR.fasta
norA.fasta                      RamR_jet.res
norA_jet.res                    RamR_normPred_evolCombi.txt
norA_normPred_evolCombi.txt     RamR.out
norA.out                        sp.fasta
NORA_STAAU_Miller_2025.csv      sp_jet.res
NORA_STAAU_Miller_2025.txt      sp_normPred_evolCombi.txt
P11436.fasta                    sp.out
P11436_jet.res

In [4]:
df1 = pd.read_csv("../processed_data/ALPH_ELIME_Markin_2021.csv").set_index("mutant")
escott_df = pd.read_csv("../model_scores/ESCOTT/ALPH_normPred_evolCombi.txt", names=("mut", "ESCOTT_score"), sep=" ").set_index("mut")

df1['ESCOTT_score'] = escott_df['ESCOTT_score']
df1.to_csv("../model_scores/ESCOTT/ALPH_ELIME_Markin_2021.csv")

In [2]:
escott_file_codes = {"ALPH_ELIME_Markin_2021": 'ALPH',
                     "NORA_STAAU_Miller_2025": 'norA',
                     "HTHTR_SALTY_dOelsnitz_2025": 'RamR',
                     "AMIE_PSEAE_Wrenbeck_2017": 'P11436',
                     'DLG4_HUMAN_Zarin_2024': 'PSD95pdz3',
                     'PHO4_YEAST_Aditham_2021': 'PHO4',
                     'BLAT_ECOLX_Stiffler_2015': 'P62593',
                     'MNTH_DEIRA_Berry_2025': 'sp'}

# for key,filecode in escott_file_codes.items():

#     df1 = pd.read_csv(f"../processed_data/{key}.csv").set_index("mutant")
#     escott_df = pd.read_csv(f"../model_scores/ESCOTT/{filecode}_normPred_evolCombi.txt", names=("mut", "ESCOTT"), sep=" ").set_index("mut")
    
#     df1['ESCOTT'] = escott_df['ESCOTT']
#     df1.to_csv(f"../model_scores/ESCOTT/{key}.csv")

In [ ]:
gemme_file_codes = {'DLG4_HUMAN_Zarin_2025': 'PSD95pdz3'}

In [4]:
escott_file_codes

{'ALPH_ELIME_Markin_2021': 'ALPH',
 'NORA_STAAU_Miller_2025': 'norA',
 'HTHTR_SALTY_dOelsnitz_2025': 'RamR',
 'AMIE_PSEAE_Wrenbeck_2017': 'P11436',
 'DLG4_HUMAN_Zarin_2024': 'PSD95pdz3',
 'PHO4_YEAST_Aditham_2021': 'PHO4',
 'BLAT_ECOLX_Stiffler_2015': 'P62593',
 'MNTH_DEIRA_Berry_2025': 'sp'}

In [3]:
for key,filecode in escott_file_codes.items():

    df1 = pd.read_csv(f"../processed_data/{key}.csv").set_index("mutant")
    gemme_df = pd.read_csv(f"../model_scores/GEMME/{key}/{filecode}_normPred_evolCombi.txt", names=("mut", "GEMME"), sep=" ").set_index("mut")
    
    df1['GEMME'] = gemme_df['GEMME']
    # df1.to_csv(f"../model_scores/GEMME/{key}.csv")

In [13]:
key="AMIE_PSEAE_Wrenbeck_2017"; filecode="P11436"
df1 = pd.read_csv(f"../processed_data/{key}.csv").set_index("mutant")
gemme_df = pd.read_csv(f"../model_scores/GEMME/{key}/{filecode}_normPred_evolCombi.txt", names=("mut", "GEMME"), sep=" ").set_index("mut")
gemme_df = gemme_df.iloc[1:].set_index(df1.index)

df1['GEMME'] = gemme_df['GEMME']
df1.to_csv(f"../model_scores/GEMME/AMIE_PSEAE_Wrenbeck_2017.csv")

In [12]:
df1

,Unnamed: 0,acetamide_fitness,propionamide_fitness,isobutyramide_fitness,specificity_category,DMS_score,n_subs,mutated_sequence,GEMME
mutant,,,,,,,,,
M1F,M1F,-1.7829,-1.3118,-0.6809,inactive,-1.7829,1,FRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,0.000000
M1W,M1W,NaN,NaN,-0.5174,other,NaN,1,WRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,0.000000
M1Y,M1Y,NaN,NaN,-0.5253,other,NaN,1,YRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,0.000000
M1P,M1P,-2.1514,-1.1457,-0.5154,inactive,-2.1514,1,PRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,0.000000
M1M,M1M,0.0000,0.0000,0.0000,native-specificity,0.0000,0,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,0.000000
...,...,...,...,...,...,...,...,...,...
G341D,G341D,0.1300,0.1685,0.0331,native-specificity,0.1300,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,-0.569700
G341E,G341E,0.0272,-0.0451,-0.0263,native-specificity,0.0272,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,-0.552309
G341H,G341H,-0.1865,-0.1954,-0.0578,native-specificity,-0.1865,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,-3.553602
G341K,G341K,0.0378,-0.1328,-0.1361,native-specificity,0.0378,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,-0.531608
G341R,G341R,-0.1259,-0.1059,-0.0193,native-specificity,-0.1259,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,-0.516307

           GEMME
mutant
M1F     0.000000
M1W     0.000000
M1Y     0.000000
M1P     0.000000
M1M     0.000000
...          ...
G341D  -0.569700
G341E  -0.552309
G341H  -3.553602
G341K  -0.531608
G341R  -0.516307

[6820 rows x 1 columns]

In [6]:
df1

,Unnamed: 0,acetamide_fitness,propionamide_fitness,isobutyramide_fitness,specificity_category,DMS_score,n_subs,mutated_sequence,GEMME
mutant,,,,,,,,,
M1F,M1F,-1.7829,-1.3118,-0.6809,inactive,-1.7829,1,FRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
M1W,M1W,NaN,NaN,-0.5174,other,NaN,1,WRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
M1Y,M1Y,NaN,NaN,-0.5253,other,NaN,1,YRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
M1P,M1P,-2.1514,-1.1457,-0.5154,inactive,-2.1514,1,PRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
M1M,M1M,0.0000,0.0000,0.0000,native-specificity,0.0000,0,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
...,...,...,...,...,...,...,...,...,...
G341D,G341D,0.1300,0.1685,0.0331,native-specificity,0.1300,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
G341E,G341E,0.0272,-0.0451,-0.0263,native-specificity,0.0272,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
G341H,G341H,-0.1865,-0.1954,-0.0578,native-specificity,-0.1865,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
G341K,G341K,0.0378,-0.1328,-0.1361,native-specificity,0.0378,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN
G341R,G341R,-0.1259,-0.1059,-0.0193,native-specificity,-0.1259,1,MRHGDISSSNDTVGVAVVNYKMPRLHTAAEVLDNARKIAEMIVGMK...,NaN

In [14]:
for key,filecode in escott_file_codes.items():

    df1 = pd.read_csv(f"../processed_data/{key}.csv").set_index("mutant")
    gemme_df = pd.read_csv(f"../model_scores/GEMME/{filecode}_normPred_evolCombi.txt", names=("mut", "GEMME"), sep=" ").set_index("mut")
    
    df1['GEMME'] = escott_df['GEMME']
    df1.to_csv(f"../model_scores/GEMME/{key}.csv")

         GEMME
mut
A41C -3.792415
A41D -3.162204
A41E -0.642309
A41F -4.199586
A41G -1.768147
...        ...
Y95S -3.692451
Y95T -1.278633
Y95V -3.316176
Y95W -3.169560
G1G   0.000000

[1773 rows x 1 columns]

In [13]:
df1

,Unnamed: 0,CRIPT,K-4A,K-4C,K-4D,K-4E,K-4F,K-4G,K-4H,K-4I,...,Y-5R,Y-5S,Y-5T,Y-5V,Y-5W,AbundancePCA_fitness,specificity_category,DMS_score,n_subs,mutated_sequence
mutant,,,,,,,,,,,,,,,,,,,,,
A41C,A343C,0.026520,-0.298913,-0.413703,-0.539565,-0.397802,-0.831110,NaN,-0.257920,-0.297779,...,NaN,-0.256509,-0.177787,NaN,NaN,-0.204364,native-specificity,0.026520,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILCGGPAD...
A41D,A343D,0.069296,-0.378548,-0.469385,-0.628299,-0.389554,-0.820175,-0.685025,-0.401440,-0.424549,...,-0.299154,-0.551633,-0.276364,-0.133116,-0.118303,0.017223,altered-specificity,0.069296,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILDGGPAD...
A41E,A343E,0.084897,-0.367243,-0.389051,-0.492823,-0.399576,-0.420478,-0.560091,-0.294143,-0.203114,...,-0.085143,-0.206459,-0.177715,-0.100874,0.019442,0.090430,altered-specificity,0.084897,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILEGGPAD...
A41F,A343F,0.005199,NaN,NaN,-0.513716,-0.448537,NaN,NaN,-0.325517,NaN,...,NaN,NaN,NaN,-0.100866,NaN,-0.300827,native-specificity,0.005199,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILFGGPAD...
A41G,A343G,0.083095,-0.296832,-0.238344,-0.377707,-0.292105,-0.363087,-0.452941,-0.195322,-0.185427,...,0.055866,-0.099281,-0.141311,-0.039679,0.137141,-0.215962,native-specificity,0.083095,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILGGGPAD...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Y95R,Y397R,NaN,NaN,-0.523860,-0.623260,-0.735999,-0.702423,-0.684318,-0.463543,-0.546185,...,-0.257730,NaN,-0.310440,-0.331655,-0.287704,NaN,native-specificity,NaN,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPAD...
Y95S,Y397S,NaN,-0.487962,-0.613474,-0.518967,-0.507763,-0.461042,-0.733811,-0.425893,-0.291379,...,-0.092979,-0.227315,-0.263941,-0.272664,-0.009446,NaN,native-specificity,NaN,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPAD...
Y95T,Y397T,NaN,-0.529604,-0.633289,-0.392887,-0.498434,-0.522433,-0.535160,-0.471773,-0.494210,...,-0.183203,-0.297585,NaN,-0.214401,-0.160755,NaN,native-specificity,NaN,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPAD...
Y95V,Y397V,NaN,-0.352307,-0.387348,NaN,-0.444610,-0.724575,-0.589291,-0.685804,-0.294229,...,-0.114743,-0.159501,-0.333654,-0.256743,0.037321,NaN,native-specificity,NaN,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPAD...
Y95W,Y397W,NaN,-0.539345,-0.353026,-0.562085,-0.377603,-0.483909,-0.420551,-0.331542,-0.386729,...,-0.051154,-0.230543,-0.237199,-0.176414,NaN,NaN,native-specificity,NaN,1,GEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPAD...

In [ ]:
df1 = pd.read_csv("../processed_data/ALPH_ELIME_Markin_2021.csv").set_index("mutant")
escott_df = pd.read_csv("../model_scores/ESCOTT/ALPH_normPred_evolCombi.txt", names=("mut", "ESCOTT_score"), sep=" ").set_index("mut")

df1['ESCOTT_score'] = escott_df['ESCOTT_score']
df1.to_csv("../model_scores/ESCOTT/ALPH_ELIME_Markin_2021.csv")